name: Media-Search-bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build media-search-bot
      run: |
        docker build -t botxtg/media-search-bot:latest .
    - name: docker push
      run: |
        docker push botxtg/media-search-bot:latest
